paper/urls.py
from django.urls import path
from . import views

app_name = 'paper'
urlpatterns = [
    path('<int:paper_id>/', views.paper_view, name='paper'),
    path('method/<int:method_id>/', views.method_view, name='method'),
]

paper/models.py
from django.db import models


# class Result(models.Model):
#     value = models.FloatField()


class Author(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Conference(models.Model):
    title = models.CharField(max_length=300)
    short_title = models.CharField(max_length=30)

    def __str__(self):
        return self.short_title


class Paper(models.Model):
    title = models.CharField(max_length=200)
    problem = models.TextField(max_length=500)
    solution = models.TextField(max_length=2000)
    conference = models.ForeignKey(Conference, on_delete=models.CASCADE)
    text_url = models.URLField()
    code_url = models.URLField(blank=True)
    project_url = models.URLField(blank=True)
    date_published = models.DateField(verbose_name="publication date")

    DATASET_TYPE = 0
    METHOD_TYPE = 1
    THEORY_TYPE = 2
    TYPE_CHOICES = (
        (DATASET_TYPE, 'Dataset'),
        (METHOD_TYPE, 'Method'),
        (THEORY_TYPE, 'Theory'),
    )

    type = models.IntegerField(choices=TYPE_CHOICES)
    authors = models.ManyToManyField(Author)

    def __str__(self):
        return self.title


class Method(models.Model):
    title = models.CharField(max_length=100)
    short_title = models.CharField(max_length=20)
    description = models.TextField(max_length=3200)
    orig_paper = models.ForeignKey(
        Paper, on_delete=models.CASCADE, verbose_name='Original paper',
    )

    def __str__(self):
        return self.short_title

paper/views.py
from django.shortcuts import render, get_object_or_404
from .models import Paper, Method


def paper_view(request, paper_id):
    paper = get_object_or_404(Paper, pk=paper_id)
    context = {
        'paper': paper,
        'methods': Method.objects.filter(orig_paper_id=paper_id),
    }
    return render(request, "paper/paper.html", context)


def method_view(request, method_id):
    method = get_object_or_404(Method, pk=method_id)
    context = {'method': method}
    return render(request, "paper/method.html", context)

paper/templates/paper/paper.html
{% extends "base_element.html" %}
{% load static %}

{% block css-include %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/paper.css' %}"/>
{% endblock %}

{% block content %}
    <header>{{ paper.title }}</header>
    <div id="info">
        {% for author in paper.authors.all %}
            {{ author.name }}{%if not forloop.last%},{%endif%}
        {% endfor %} ({{ paper.conference.short_title }},
                      {{ paper.date_published }}), 10 cites, 3 links</div>
    {# TODO: automatic cites and links determination #}
    <table id="content">
        <tr class="content-row">
            <td class="elem-header">Problem</td>
            <td class="elem-text">{{ paper.problem }}</td>
        </tr>
        <tr class="content-row">
            <td class="elem-header">Type</td>
            <td class="elem-text">{{ paper.get_type_display }}.</td>
        </tr>
        <tr class="content-row">
            <td class="elem-header">Solution</td>
            <td class="elem-text">{{ paper.solution }}</td><!-- TODO: justify with carry-over text? -->
        </tr>
        <tr class="content-row">
            <td class="elem-header">Methods</td>
            <td class="elem-text">
                {% for method in methods %}
                    <a href="{% url "paper:method" method.id %}">{{ method.short_title }}</a>{%if not forloop.last%},{%endif%}
                {% endfor %}
            </td>
        </tr>
        <tr class="content-row">
            <td class="elem-header">Results</td>
            <td class="elem-text">
                <a href="#0">QUASAR-T</a> (<a href="#0">precision</a>, <a href="#0">recall</a>).
                <a href="#1">MF-e</a> (0.20, 0.43),
                <a href="#2">MF-i</a> (0.50, 0.32),
                <a href="#3">Richardson et al., 2013/SW</a> (0.93, 0.99),
                <a href="#4">Richardson et al., 2013/SW+D</a> (0.61, 0.41)
                <br/><br/> <!-- TODO: make it with margin/padding -->
                <a href="#0">QUASAR-S</a> (<a href="#0">precision</a>, <a href="#0">recall</a>).
                <a href="#1">MF-e</a> (0.20, 0.43),
                <a href="#2">MF-i</a> (0.50, 0.32),
                <a href="#3">Richardson et al., 2013/SW</a> (0.92, 0.99),
                <a href="#4">Richardson et al., 2013/SW+D</a> (0.69, 0.41)
            </td>
        </tr>
    </table>
    <footer>
        <a href="{{ paper.text_url }}">url</a>,
        <a href="{{ paper.code_url }}">code</a>
{# TODO: project url, make code url optional #}
    </footer>
{% endblock content %}