elements/urls.py
from django.urls import path
from . import views

app_name = 'elements'
urlpatterns = [
  path('paper/<int:paper_id>/', views.paper_view, name='paper'),
  path('method/<int:method_id>/', views.method_view, name='method'),
  path('dataset/<int:dataset_id>/', views.dataset_view, name='dataset'),
  path('metric/<int:metric_id>/', views.metric_view, name='metric'),
  path('link_type/<int:link_type_id>/', views.link_type_view, name='link_type'),
  path('paper_type/<int:paper_type_id>/', views.paper_type_view,
       name='paper_type'),
  path('text_result/<int:text_result_id>/', views.text_result_view,
       name='text_result'),
]

paper/urls.py
from django.urls import path
from . import views

app_name = 'paper'
urlpatterns = [
    path('<int:paper_id>/', views.paper_view, name='paper'),
    path('method/<int:method_id>/', views.method_view, name='method'),
]

elements/models.py
from django.db import models


class Metric(models.Model):
  name = models.CharField(max_length=100)
  description = models.TextField(max_length=2000)
  to_complete = models.TextField(max_length=2000, blank=True)
  # TODO: add automatically checked range?
  # TODO: add some field for useful link(s). Also might be useful in other places

  def __str__(self):
    return self.name


class Author(models.Model):
  name = models.CharField(max_length=100)

  def __str__(self):
    return self.name


class Conference(models.Model):
  name = models.CharField(max_length=255)
  short_name = models.CharField(max_length=30)

  def __str__(self):
    return self.short_name


class PaperType(models.Model):
  name = models.CharField(max_length=100)
  description = models.TextField(max_length=3200)

  def __str__(self):
    return self.name


class Paper(models.Model):
  title = models.CharField(max_length=200)
  problem = models.TextField(max_length=500)
  solution = models.TextField(max_length=2000)
  conference = models.ForeignKey(Conference, on_delete=models.CASCADE)
  text_url = models.URLField()
  code_url = models.URLField(blank=True)
  project_url = models.URLField(blank=True)
  date_published = models.DateField(verbose_name="publication date")

  types = models.ManyToManyField(PaperType)
  authors = models.ManyToManyField(Author, through='Authorship')
  to_complete = models.TextField(max_length=2000, blank=True)

  def __str__(self):
    return self.title


class Authorship(models.Model):
  paper = models.ForeignKey(Paper, on_delete=models.CASCADE)
  author = models.ForeignKey(Author, on_delete=models.CASCADE)
  order_number = models.IntegerField()


class Dataset(models.Model):
  name = models.CharField(max_length=100)
  description = models.TextField(max_length=2000)
  paper = models.ForeignKey(Paper, on_delete=models.CASCADE)
  to_complete = models.TextField(max_length=2000, blank=True)

  def __str__(self):
    return self.name


class Method(models.Model):
  name = models.CharField(max_length=100)
  short_name = models.CharField(max_length=20)
  description = models.TextField(max_length=3200)
  paper = models.ForeignKey(
      Paper, on_delete=models.CASCADE, verbose_name='Original elements',
  )
  visual_description = models.ImageField(upload_to='uploads', blank=True)
  to_complete = models.TextField(max_length=2000, blank=True)

  def __str__(self):
    return self.short_name


class ValueResult(models.Model):
  value = models.FloatField()
  dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)
  metric = models.ForeignKey(Metric, on_delete=models.CASCADE)
  method = models.ForeignKey(Method, on_delete=models.CASCADE)
  paper = models.ForeignKey(Paper, on_delete=models.CASCADE)
  # TODO: how to display?
  configuration = models.TextField(max_length=1000, blank=True)
  # TODO: add check that there are no two results for the same method/dataset
  # TODO: think about rewriting it in the actual format:
  #       dataset: list of metrics, list of methods-values
  to_complete = models.TextField(max_length=2000, blank=True)

  def __str__(self):
    return "{}/{}/{}/{:.2f}".format(self.dataset.name, self.method.name,
                                    self.metric.name, self.value)


class TextResult(models.Model):
  short_description = models.CharField(max_length=100)
  detailed_description = models.TextField(max_length=3000)
  visual_description = models.ImageField(upload_to='uploads', blank=True)
  paper = models.ForeignKey(Paper, on_delete=models.CASCADE)
  to_complete = models.TextField(max_length=2000, blank=True)

  def __str__(self):
    return self.short_description


class LinkType(models.Model):
  name = models.CharField(max_length=100)
  description = models.TextField(max_length=3200)

  def __str__(self):
    return self.name


class Link(models.Model):
  # TODO: add check that can't link to itself
  type = models.ForeignKey(LinkType, on_delete=models.CASCADE)
  src_paper = models.ForeignKey(
    Paper,
    on_delete=models.CASCADE,
    related_name='src_paper'
  )
  dst_paper = models.ForeignKey(
    Paper,
    on_delete=models.CASCADE,
    related_name='dst_paper',
  )

  def __str__(self):
    return "{}--{}--{}".format(
      self.src_paper.title, self.type, self.dst_paper.title,
    )

paper/models.py
from django.db import models


# class Result(models.Model):
#     value = models.FloatField()


class Author(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Conference(models.Model):
    title = models.CharField(max_length=300)
    short_title = models.CharField(max_length=30)

    def __str__(self):
        return self.short_title


class Paper(models.Model):
    title = models.CharField(max_length=200)
    problem = models.TextField(max_length=500)
    solution = models.TextField(max_length=2000)
    conference = models.ForeignKey(Conference, on_delete=models.CASCADE)
    text_url = models.URLField()
    code_url = models.URLField(blank=True)
    project_url = models.URLField(blank=True)
    date_published = models.DateField(verbose_name="publication date")

    DATASET_TYPE = 0
    METHOD_TYPE = 1
    THEORY_TYPE = 2
    TYPE_CHOICES = (
        (DATASET_TYPE, 'Dataset'),
        (METHOD_TYPE, 'Method'),
        (THEORY_TYPE, 'Theory'),
    )

    type = models.IntegerField(choices=TYPE_CHOICES)
    authors = models.ManyToManyField(Author)

    def __str__(self):
        return self.title


class Method(models.Model):
    title = models.CharField(max_length=100)
    short_title = models.CharField(max_length=20)
    description = models.TextField(max_length=3200)
    orig_paper = models.ForeignKey(
        Paper, on_delete=models.CASCADE, verbose_name='Original paper',
    )

    def __str__(self):
        return self.short_title

elements/views.py
from django.shortcuts import render, get_object_or_404
from .models import Paper, Method, ValueResult, Dataset, \
                    Metric, Link, LinkType, PaperType, TextResult


def paper_view(request, paper_id):
  """View to create a paper page.
  In the database, results are stored as list of
  tuples: (value, dataset, metric, method, configuration, etc.). This is not
  a convenient representation for template table, since we need to have one
  table for each dataset structured as
          metric1 metric2
  method1  value  value
  method2  value  value
  .....................
  Thus we reformat the results data structure here to a more convenient way.
  Exactly, we create a dictionary dataset_results of the following form:
  {
      dataset1: {
          metric1: [(method1, value1, config1), (method2, value2, config2), ...]
          ...
      }
      ...
  }

  After that we create another dictionary results_for_template in the following
  form:
  {
      dataset1: [
                  (
                    [metric1, metric2, ...],
                    [
                      [method1, (value1, config1), (value2, config2)],
                      [method2, (value1, config1), (value2, config2)],
                      ...
                    ]
                  )
                ]
  }
  which is what is passed to the template.
  """
  paper = get_object_or_404(Paper, pk=paper_id)
  # TODO: rewrite as SQL so that it is always fast?
  results = ValueResult.objects.filter(paper_id=paper_id)

  # TODO: make a unittest to check this functionality

  datasets_results = {}
  for result in results:
    if result.dataset not in datasets_results:
      datasets_results[result.dataset] = {}
    if result.metric not in datasets_results[result.dataset]:
      datasets_results[result.dataset][result.metric] = []
    datasets_results[result.dataset][result.metric].append(
      (result.method, result.value, result.configuration),
    )
  results_for_template = {}
  for dataset, metrics_dict in datasets_results.items():
    results_for_template[dataset] = (
      sorted(metrics_dict.keys(), key=lambda x: x.name), []
    )
    results_lists = []
    # results_for_template[dataset][0] = sorted(metrics_dict.keys())
    for metric in results_for_template[dataset][0]:
      results_lists.append(
        sorted(metrics_dict[metric], key=lambda x: x[0].short_name),
      )
    # results_lists = [
    #   [(method1, value1, config1), (method2, value2, config2)], <- for metric1
    #   [(method1, value1, config1), (method2, value2, config2)], <- for metric2
    #   .......
    # ]
    # sorted by method.short_name
    # TODO: add support for not equal lists
    for result_tuples in zip(*results_lists):
      results_row = [result_tuples[0][0]]
      for result_tuple in result_tuples:
        results_row.append(result_tuple[1:])
      results_for_template[dataset][1].append(results_row)

  context = {
    'paper': paper,
    'authors': paper.authors.all().order_by('authorship__order_number'),
    'methods': Method.objects.filter(paper_id=paper_id),
    'value_results': results_for_template,
    'text_results': TextResult.objects.filter(paper_id=paper_id),
    'links_to_current': Link.objects.filter(dst_paper_id=paper_id),
    'links_from_current': Link.objects.filter(src_paper_id=paper_id),
  }
  return render(request, "elements/paper.html", context)


def method_view(request, method_id):
  method = get_object_or_404(Method, pk=method_id)
  context = {'method': method}
  return render(request, "elements/method.html", context)


def text_result_view(request, text_result_id):
  text_result = get_object_or_404(TextResult, pk=text_result_id)
  context = {'result': text_result}
  return render(request, "elements/text_result.html", context)


def dataset_view(request, dataset_id):
  dataset = get_object_or_404(Dataset, pk=dataset_id)
  context = {'dataset': dataset}
  return render(request, "elements/dataset.html", context)


def metric_view(request, metric_id):
  metric = get_object_or_404(Metric, pk=metric_id)
  context = {'metric': metric}
  return render(request, "elements/metric.html", context)


def link_type_view(request, link_type_id):
  link_type = get_object_or_404(LinkType, pk=link_type_id)
  context = {'link_type': link_type}
  return render(request, "elements/link_type.html", context)


def paper_type_view(request, paper_type_id):
  paper_type = get_object_or_404(PaperType, pk=paper_type_id)
  context = {'paper_type': paper_type}
  return render(request, "elements/paper_type.html", context)

paper/views.py
from django.shortcuts import render, get_object_or_404
from .models import Paper, Method


def paper_view(request, paper_id):
    paper = get_object_or_404(Paper, pk=paper_id)
    context = {
        'paper': paper,
        'methods': Method.objects.filter(orig_paper_id=paper_id),
    }
    return render(request, "paper/paper.html", context)


def method_view(request, method_id):
    method = get_object_or_404(Method, pk=method_id)
    context = {'method': method}
    return render(request, "paper/method.html", context)

elements/templates/elements/dataset.html
{% extends "base_element.html" %}
{% load static %}
{% load internal_links %}

{% block css-include %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/method.css' %}"/>
{% endblock %}

{% block content %}
    <header>{{ dataset.name }}</header>
    <div id="description">{{ dataset.description|internal_links }}</div>
{# TODO: add fancy things like what's state of the art, etc. #}
{% endblock content %}

elements/templates/elements/link_type.html
{% extends "base_element.html" %}
{% load static %}
{% load internal_links %}

{% block css-include %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/method.css' %}"/>
{% endblock %}

{% block content %}
    <header>{{ link_type.name }}</header>
    <div id="description">{{ link_type.description|internal_links }}</div>
{% endblock content %}

elements/templates/elements/method.html
{% extends "base_element.html" %}
{% load static %}
{% load internal_links %}

{% block css-include %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/method.css' %}"/>
{% endblock %}

{% block content %}
    <header>{{ method.name }}</header>
    <div id="description">{{ method.description|internal_links }}</div>
    {% if method.visual_description %}
    <div id="visual-description">
        <img src="{{ method.visual_description.url }}"/>
    </div>
    {% endif %}
{# TODO: add fancy things like in how many papers used, where performs good, etc. #}
{% endblock content %}

elements/templates/elements/metric.html
{% extends "base_element.html" %}
{% load static %}
{% load internal_links %}

{% block css-include %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/method.css' %}"/>
{% endblock %}

{% block content %}
    <header>{{ metric.name }}</header>
    <div id="description">{{ metric.description|internal_links }}</div>
{# TODO: add link with more info, range, etc? #}
{% endblock content %}

elements/templates/elements/paper.html
{% extends "base_element.html" %}
{% load static %}
{% load internal_links %}


{% block css-include %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/paper.css' %}"/>
{% endblock %}

{% block js-include %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/paper.js' %}"></script>
{% endblock %}

{% block content %}
    <header>{{ paper.title }}</header>
    <div id="info">
        {% for author in authors %}
            {{ author.name }}{%if not forloop.last%},{%endif%}
        {% endfor %} ({{ paper.conference.short_name }},
                      {{ paper.date_published }}), x cites, y links</div>
    {# TODO: automatic cites and links determination #}
    <table id="content">
        <tr class="content-row">
            <td class="elem-header">Problem</td>
            <td class="elem-text">{{ paper.problem|internal_links }}</td>
        </tr>
        <tr class="content-row">
            <td class="elem-header">Type</td>
            <td class="elem-text">
                {% for type in paper.types.all %}
                    <a href="{% url "elements:paper_type" type.id %}">
                        {{ type.name }}</a>{%if not forloop.last%},{% else %}.{%endif%}
                {% endfor %}
            </td>
        </tr>
        <tr class="content-row">
            <td class="elem-header">Solution</td>
            <td class="elem-text">{{ paper.solution|internal_links }}</td><!-- TODO: justify with carry-over text? -->
        </tr>
        <tr class="content-row">
            <td class="elem-header">Methods</td>
            <td class="elem-text">
                {% for method in methods %}
                    <a href="{% url "elements:method" method.id %}">
                        {{ method.short_name }}</a>{%if not forloop.last%},{%endif%}
                {% endfor %}
            </td>
        </tr>
        <tr class="content-row">
            <td class="elem-header">Quantitative results</td>
            <td class="elem-text">
            {% for dataset, results_tuple in value_results.items %}
                <table class="dataset-results">
                    <tr class="dataset-name-row">
                        <td colspan="3">
                            <a href="{% url "elements:dataset" dataset.id %}">
                                {{ dataset.name }}
                            </a>
                        </td>
                    </tr>
                    <tr class="metrics-row">
                        <td></td>
                        {% for metric in results_tuple.0 %}
                        <td>
                            <a href="{% url "elements:metric" metric.id %}">
                                {{ metric.name }}
                            </a>
                        </td>
                        {% endfor %}
                    </tr>
                {% for result_row in results_tuple.1 %}
                    <tr class="result-row">
                        <td>
                            <a class="result-name" href="{% url "elements:method" result_row.0.id %}">
                                {{ result_row.0.short_name }}
                            </a>

                        </td>
                    {% for value, configuration in result_row|slice:"1:" %}
                        <td class="value-container" id="value-{{ dataset.id }}-{{ forloop.parentloop.counter0 }}-{{ forloop.counter0 }}">
                            <div class="result-value">{{ value }}</div>
                            <div id="config-{{ dataset.id }}-{{ forloop.parentloop.counter0 }}-{{ forloop.counter0 }}" class="result-config">
                                {{ configuration|internal_links }}
                            </div>
                        </td>
                    {% endfor %}
                    </tr>
                {% endfor %}
                </table>
            {% endfor %}
            </td>
        </tr>
        <tr class="content-row">
            <td class="elem-header">Qualitative results</td>
            <td class="elem-text">
            {% for result in text_results %}
                <a href="{% url "elements:text_result" result.id %}">
                    {{ result.short_description }}</a>{%if not forloop.last%},{%endif%}
            {% endfor %}
            </td>
        </tr>

        <tr class="content-row">
            <td class="elem-header">Extends</td>
            <td class="elem-text">
            {% for link in links_to_current %}
                <div class="link">
                    <a href="{% url "elements:paper" link.src_paper.id %}">
                        {{ link.src_paper.title }}
                    </a> as
                    <a href="{% url "elements:link_type" link.type.id %}">
                        {{ link.type.name }}
                    </a>
                </div>
            {% endfor %}
            </td>
        </tr>
        <tr class="content-row">
            <td class="elem-header">Extended by</td>
            <td class="elem-text">
            {% for link in links_from_current %}
                <div class="link">
                    <a href="{% url "elements:paper" link.dst_paper.id %}">
                        {{ link.dst_paper.title }}
                    </a> as
                    <a href="{% url "elements:link_type" link.type.id %}">
                        {{ link.type.name }}
                    </a>
                </div>

            {% endfor %}
            </td>
        </tr>
    </table>
    <footer>
        <a href="{{ paper.text_url }}">url</a>,
        <a href="{{ paper.code_url }}">code</a>
{# TODO: project url, make code url optional #}
    </footer>
{% endblock content %}

elements/templates/elements/paper_type.html
{% extends "base_element.html" %}
{% load static %}
{% load internal_links %}

{% block css-include %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/method.css' %}"/>
{% endblock %}

{% block content %}
    <header>{{ paper_type.name }}</header>
    <div id="description">{{ paper_type.description|internal_links }}</div>
{% endblock content %}

elements/templates/elements/text_result.html
{% extends "base_element.html" %}
{% load static %}
{% load internal_links %}

{% block css-include %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/method.css' %}"/>
{% endblock %}

{% block content %}
    <header>{{ result.short_description }}</header>
    <div id="description">{{ result.detailed_description|internal_links }}</div>
    {% if result.visual_description %}
    <div id="visual-description">
        <img src="{{ result.visual_description.url }}"/>
    </div>
    {% endif %}
{% endblock content %}